my:
  greeting: Hello World
  list:
    values: one, two, three

app:
  name: Config
  description: Welcome to ${app.name}



db:
  connection: String here
  host: "127.0.0.1"
  port: "1200"


management.endpoints.web.exposure.include: "*"
